# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
     - main

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.7"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest
        pip install seleniumbase
        pip install pandas
        pip install pip install snowflake-connector-python
        sbase install chromedriver latest

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest test_example.py  --junitxml="test-result.xml"  --headless --dashboard -o junit_suite_name=first_test
        pytest test_example2.py --junitxml="test-result2.xml" --headless --dashboard -o junit_suite_name=second_test
      
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Testsss               # Name of the check run which will be created
        path: test*.xml             # Path to test results
        reporter: java-junit        # Format of test results
